# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Q_LIP
                                 A QGIS plugin
 QGIS-Landsat Indices plugin (Q-LIP)
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-03-26
        copyright            : (C) 2021 by YAZIDI ALAOUI Otmane & SEBBAH Boutaina /FSTT
        email                : yazidiotmane@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Q_LIP class from file Q_LIP.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Q_LIP import Q_LIP
    return Q_LIP(iface)
